# Generated by Django 4.2.4 on 2023-08-28 19:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('ETFTickers', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ETFInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ETFHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('asset_class', models.CharField(max_length=100)),
                ('market_value', models.FloatField()),
                ('weight', models.FloatField()),
                ('notional_value', models.FloatField()),
                ('shares', models.FloatField()),
                ('cusip', models.CharField(max_length=10)),
                ('isin', models.CharField(max_length=10)),
                ('sedol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('fx_rate', models.FloatField()),
                ('maturity', models.DateField()),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etfinformation')),
            ],
        ),
    ]
