# Generated by Django 4.2.4 on 2023-08-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('AUM', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('inception_date', models.DateField()),
                ('LEI', models.CharField(max_length=20)),
            ],
        ),
    ]
