# Generated by Django 4.2.4 on 2023-08-18 01:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFInformation',
            fields=[
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('AUM', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('inception_date', models.DateField()),
                ('LEI', models.CharField(default=api.models.generate_unique_code, max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ETF_information',
        ),
    ]
