# Generated by Django 4.2.4 on 2023-08-24 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_etfinformation_delete_etf_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfinformation',
            name='host',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ETFHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('shares', models.FloatField()),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etfinformation')),
            ],
        ),
    ]
