# Generated by Django 4.2.4 on 2023-09-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_etfholding_cusip_alter_etfholding_fx_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfinformation',
            name='expense_ratio',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
