# Generated by Django 4.2.4 on 2023-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etfinformation_expense_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfinformation',
            name='expense_ratio',
            field=models.FloatField(max_length=5),
        ),
    ]
