# Generated by Django 4.2.4 on 2023-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etfinformation_host_etfholdings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETFname', models.CharField(max_length=100)),
            ],
        ),
    ]
