# Generated by Django 4.2.4 on 2023-08-26 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blend'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='host',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
