# Generated by Django 4.2.4 on 2023-08-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blend_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blend',
            old_name='ETFname',
            new_name='ETFnames',
        ),
    ]
