# Generated by Django 4.2.4 on 2023-08-26 22:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_etfname_blend_etfnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='ETFnames',
        ),
        migrations.AddField(
            model_name='blend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blend',
            name='host',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('ticker', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etfs', to='api.blend')),
            ],
        ),
    ]
