# Generated by Django 4.2.4 on 2023-08-27 00:20

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_blend_created_at_blend_etftickers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blend',
            name='id',
        ),
        migrations.AddField(
            model_name='blend',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='blend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
