# Generated by Django 4.2.4 on 2023-09-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETFInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
                ('expense_ratio', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ETFHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('asset_class', models.CharField(max_length=100)),
                ('market_value', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('notional_value', models.CharField(max_length=100)),
                ('shares', models.CharField(max_length=100)),
                ('cusip', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=20)),
                ('sedol', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('fx_rate', models.CharField(max_length=100)),
                ('maturity', models.CharField(max_length=100)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.etfinformation')),
            ],
        ),
    ]
